/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

#include "main.h"
#include <sys/stat.h>
#include "FreeRTOS.h"
#include "task.h"


#define STDIN_FILENO  0
#define STDOUT_FILENO 1
#define STDERR_FILENO 2


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;

UART_HandleTypeDef *gHuart;

void RetargetInit(UART_HandleTypeDef *huart) {
  gHuart = huart;

  /* Disable I/O buffering for STDOUT stream, so that
   * chars are sent out as soon as they are printed. */
  setvbuf(stdout, NULL, _IONBF, 0);
}




/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
	return 1;
}

int _kill(int pid, int sig)
{
	errno = EINVAL;
	return -1;
}

void _exit (int status)
{
	_kill(status, -1);
	while (1) {}		/* Make sure we hang here */
}

__attribute__((weak)) int _read(int fd, char *ptr, int len)
{
	  HAL_StatusTypeDef hstatus;

	  if (fd == STDIN_FILENO) {

	    hstatus = HAL_UART_Receive(gHuart, (uint8_t *) ptr, 1, HAL_MAX_DELAY);

	    if (hstatus == HAL_OK)
	      return 1;
	    else
	      return EIO;
	  }
	  errno = EBADF;
	  return -1;
}

__attribute__((weak)) int _write(int fd, char *ptr, int len)
{
	  HAL_StatusTypeDef hstatus;

	  if (fd == STDOUT_FILENO || fd == STDERR_FILENO) {
	    hstatus = HAL_UART_Transmit(gHuart, (uint8_t *) ptr, len, HAL_MAX_DELAY);

	    if (hstatus == HAL_OK)
	      return len;
	    else
	      return EIO;
	  }
	  errno = EBADF;
	  return -1;
}

int _close(int fd)
{
	  if (fd >= STDIN_FILENO && fd <= STDERR_FILENO)
	    return 0;

	  errno = EBADF;
	  return -1;
}


int _fstat(int fd, struct stat *st)
{
	  if (fd >= STDIN_FILENO && fd <= STDERR_FILENO) {
	    st->st_mode = S_IFCHR;
	    return 0;
	  }

	  errno = EBADF;
	  return 0;
}

int _isatty(int fd)
{
	  if (fd >= STDIN_FILENO && fd <= STDERR_FILENO)
	    return 1;

	  errno = EBADF;
	  return 0;
}

int _lseek(int fd, int ptr, int dir)
{
	  (void) fd;
	  (void) ptr;
	  (void) dir;

	  errno = EBADF;
	  return -1;
}

int _open(char *path, int flags, ...)
{
	/* Pretend like we always fail */
	return -1;
}

int _wait(int *status)
{
	errno = ECHILD;
	return -1;
}

int _unlink(char *name)
{
	errno = ENOENT;
	return -1;
}

int _times(struct tms *buf)
{
	return -1;
}

int _stat(char *file, struct stat *st)
{
	st->st_mode = S_IFCHR;
	return 0;
}

int _link(char *old, char *new)
{
	errno = EMLINK;
	return -1;
}

int _fork(void)
{
	errno = EAGAIN;
	return -1;
}

int _execve(char *name, char **argv, char **env)
{
	errno = ENOMEM;
	return -1;
}
